version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:


python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
