version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

build:
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/source/ src/tree_height_analysis_57 --force --module-first
