name: Build documentation and check links

on:
  push:
    branches: [master]
  schedule:
    - cron: '20 4 * * 1'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install doc dependencies
        run: |
          pip install -r docs/requirements-docs.txt
          pip install .
      - name: Build HTML docs
        run: sphinx-build -b html docs/source docs/build/html
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install doc dependencies
        run: |
          pip install -r docs/requirements-docs.txt
          pip install .
      - name: Check links
        run: sphinx-build -b linkcheck docs/source docs/build/linkcheck
