name: Build documentation and check links

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '20 4 * * 1'  # Her Pazartesi 07:20 Türkiye saati
  workflow_dispatch:

jobs:
  build-docs:
    name: Build HTML documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements-docs.txt
          pip install .

      - name: Build HTML docs with Sphinx
        run: sphinx-build -b html docs/source docs/build/html

  check-links:
    name: Check documentation links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements-docs.txt
          pip install .

      - name: Check for broken links
        run: sphinx-build -b linkcheck docs/source docs/build/linkcheck
