name: Bump and Release

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "pyproject.toml"
      - ".bumpversion.cfg"

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'ci: bump version to')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install bumpversion
        run: pip install bump2version

      - name: Bump version and push tag
        run: |
          bump2version patch
          git push origin HEAD --follow-tags
