name: Bump version and tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    name: Bump version and commit+push+tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure PAT for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bump version manually
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          CURRENT=$(grep -E '^version = ' pyproject.toml | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW="${MAJOR}.${MINOR}.${PATCH}"

          sed -i "s/^version = \".*\"/version = \"${NEW}\"/" pyproject.toml
          sed -i "s|^version = .*|version = \"${NEW}\"|" docs/source/conf.py
          sed -i "s|^release = .*|release = \"${NEW}\"|" docs/source/conf.py

          git add pyproject.toml docs/source/conf.py
          git commit -m "ci: bump version to ${NEW}"
          git tag "v${NEW}"
          git push origin HEAD --follow-tags
