name: Release: Version Bump and Publish to TestPyPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git for pushes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build twine sphinx

      - name: Print current version
        run: |
          grep -E '^version = ' pyproject.toml || echo "version not found"

      - name: Bump version, build dist and docs
        run: |
          CURRENT=$(grep -E '^version = ' pyproject.toml | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          echo "Current version: $CURRENT"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW"

          # Update versions
          sed -i "s/^version = \".*\"/version = \"${NEW}\"/" pyproject.toml
          sed -i "s|^version = .*|version = \"${NEW}\"|" docs/source/conf.py
          sed -i "s|^release = .*|release = \"${NEW}\"|" docs/source/conf.py

          # Commit version bump and tag
          git add pyproject.toml docs/source/conf.py
          git commit -m "ci: bump version to ${NEW}"
          git tag "v${NEW}"
          git push origin HEAD --follow-tags

      - name: Build distributions
        run: |
          rm -rf dist/
          python -m build
          ls -l dist

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*