name: Bump and Release

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "pyproject.toml"
      - ".bumpversion.cfg"
      - "docs/source/conf.py"

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'ci: bump version to')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install bump2version build

      - name: Bump version and create tag
        run: |
          bump2version patch

      - name: Build dist files
        run: |
          python -m build

      - name: Push changes and tags
        run: |
          git push origin HEAD --follow-tags
