name: Release: Bump version and publish to TestPyPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install build twine sphinx

      - name: Bump version, build dist and docs
        run: |
          # Version bump
          CURRENT=$(grep -E '^version = ' pyproject.toml | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW="${MAJOR}.${MINOR}.${PATCH}"

          # Update files
          sed -i "s/^version = \".*\"/version = \"${NEW}\"/" pyproject.toml
          sed -i "s|^version = .*|version = \"${NEW}\"|" docs/source/conf.py
          sed -i "s|^release = .*|release = \"${NEW}\"|" docs/source/conf.py

          # Clean and build
          rm -rf dist/
          python -m build --sdist --wheel
          rm -rf docs/build/html
          sphinx-build -b html docs/source docs/build/html

          # Commit and tag
          git add pyproject.toml docs/source/conf.py dist/ docs/build/html
          git commit -m "ci: bump version to ${NEW}"
          git tag "v${NEW}"
          git push origin HEAD --follow-tags

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*
