name: Bump version and create tag

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "pyproject.toml"

jobs:
  bump:
    name: Bump version and create tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bumpversion
        run: pip install bumpversion

      - name: Bump patch version
        run: bumpversion patch

      - name: Push changes and tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push
          git push --tags
