name: Release and publish to TestPyPI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'Bump version:')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git with PAT
        run: |
          git remote set-url origin \
            https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: pip install bumpversion build twine

      - name: Bump version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          bumpversion patch
          git push origin HEAD

      - name: Build dist
        run: |
          rm -rf dist/
          python -m build --sdist --wheel

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*
