name: Bump Version and Release to TestPyPI

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure PAT for Git pushes
        run: |
          git remote set-url origin \
            https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packaging tools
        run: |
          pip install build twine

      - name: Bump version and build dist
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          CURRENT=$(grep -E '^version = ' pyproject.toml | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW="${MAJOR}.${MINOR}.${PATCH}"

          sed -i "s/^version = \".*\"/version = \"${NEW}\"/" pyproject.toml
          sed -i "s|^version = .*|version = \"${NEW}\"|" docs/source/conf.py
          sed -i "s|^release = .*|release = \"${NEW}\"|" docs/source/conf.py

          rm -rf dist/
          python -m build

          git add pyproject.toml docs/source/conf.py dist/
          git commit -m "ci: bump version to ${NEW}"
          git tag "v${NEW}"
          git push origin HEAD --follow-tags

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload \
            --non-interactive \
            --repository-url https://test.pypi.org/legacy/ \
            dist/*
