name: Bump Version

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump patch version, commit & tag
        run: |
          bump2version patch
          git push origin HEAD --follow-tags