name: Final Check Tick

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  tick-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Git Config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: ✅ Add GitHub Status Check (with PAT)
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
          REPO: ${{ github.repository }}
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $PAT" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "context": "✅ Final Status",
              "description": "All tests passed and CI is complete.",
              "target_url": "https://github.com/'"$REPO"'/actions/runs/'"${{ github.event.workflow_run.id }}"'"
            }'
