name: Final Status Check

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  add-final-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with PAT_TOKEN
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Mark check as passed ✅
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
            -f state=success \
            -f context="✅ Final Status" \
            -f description="All CI tests passed." \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
