name: Final Check Tick

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  tick-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: ✅ Set GitHub Status Check using PAT
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
          REPO: ${{ github.repository }}
          PAT: ${{ secrets.PAT_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $PAT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d "$(jq -n \
              --arg state "success" \
              --arg context "✅ Final Status" \
              --arg description "All tests passed and CI is complete." \
              --arg target_url "https://github.com/$REPO/actions/runs/$RUN_ID" \
              '{state: $state, context: $context, description: $description, target_url: $target_url}')"
