name: Status Check

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  status-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install . pytest

      - name: Run tests
        run: pytest
